spring:
  datasource:
    url: jdbc:mysql://db:3306/jichan?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.jichan: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.context.config: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    p6spy: info