spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.jichan: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.context.config: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    p6spy: info