logging:
  level:
    com.jichan: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.context.config: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG