spring:
  application:
    name: jichan
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: false
        use_sql_comments: false
    open-in-view: false
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  forward-headers-strategy: native

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

jichan:
  server:
    address: ${FRONTEND_ADDRESS}

encryption:
  key: ${ENC_KEY}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j
      log-format: "%(executionTime)ms | %(sql)"

logging:
  level:
    com.jichan: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.context.config: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    p6spy: info